on:
  push:
    # Sequence of patterns matched against refs/tags
    branch:
    - main
    
name: Create Release

jobs:
  update-dependent-repositories:
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        repository:
          - denis-tingaikin/actions-testing-repository-b
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: ${{ matrix.repository }}
          repository: ${{ matrix.repository }}
          token: ${{ secrets.MY_TOKEN }}
      - name: push tag
        run:  |
         git tag -f ${GITHUB_REF#refs/*/}
         git push -f origin ${GITHUB_REF#refs/*/} 
        working-directory: ${{ matrix.repository }}
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: get tag
        run: echo '::set-output name=tag::'${GITHUB_REF#refs/*/}
        id: get-tag-step
      - uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true # default: false
          tag_name: ${{ steps.get-tag-step.outputs.tag }}
          repo: ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
