on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Testing
    steps:
    - name: Checkout files
      uses: actions/checkout@v2
      with:
        repository: denis-tingajkin/actions-testing-repository-b
        token: ${{ secrets.MY_TOKEN }}
        path: './mydir/test'
    - name: Test sync-files
      uses: denis-tingajkin/sync-files@main
      with:
        git-author-email: 'denis.tingajkin@xored.com'
        git-author-name: 'Denis Tingajkin'
        src-branch-name: master
        src-repository: networkservicemesh/sdk
        allow-files-pattern: (.*\.yaml|.*\.yml)
        directory: './mydir/test'
        exclude-files: |
          .github/workflows/main.yaml
