on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
  # hello_world_job:
  #   runs-on: ubuntu-latest
  #   name: Testing
  #   steps:
  #   - name: Checkout files
  #     uses: actions/checkout@v2
  #     with:
  #       repository: denis-tingajkin/actions-testing-repository-b
  #       token: ${{ secrets.MY_TOKEN }}
  #       path: './mydir/test'
  #   - name: Test sync-files
  #     uses: denis-tingajkin/sync-files@main
  #     with:
  #       git-author-email: 'denis.tingajkin@xored.com'
  #       git-author-name: 'Denis Tingajkin'
  #       sync-branch-name: main
  #       sync-ignore-file-name: .templateignore
  #       sync-repository: ${{ github.repository }}
  #       allow-files-pattern: (.*\.yaml|.*\.yml)
  #       working-directory: './mydir/test'
  #       exclude-files: |
  #         .github/workflows/main.yaml
