---
name: Release
on:
  workflow_run:
    types:
      - completed
    workflows:
      - 'ci'
jobs:
  print-env:
    name: print envs
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.workflow_run.head_branch, 'release/') }}
    steps:
      - name: Get tag
        run: |
          branch=${{github.event.workflow_run.head_branch}}
          echo '::set-output name=tag::'${branch#release/}
        id: get-tag-step
      - uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true
          tag_name: refs/tags/${{ steps.get-tag-step.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
        with:
          tag_name: refs/tags/${{ steps.get-tag-step.outputs.tag }}
          release_name: ${{ steps.get-tag-step.outputs.tag }}
          draft: false
          prerelease: false
  update-dependent-repositories:
    strategy:
      matrix:
        repository:
          - actions-testing-repository-b
    name: Update ${{ matrix.repository }}
    needs: create-release
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.workflow_run.head_branch, 'release/') }}
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v2
        with:
          path: ${{ github.repository }}
          repository: ${{ github.repository }}
          token: ${{ secrets.MY_TOKEN }}
      - name: Get tag
        run: |
          branch=${{github.event.workflow_run.head_branch}}
          echo '::set-output name=tag::'${branch#release/}
        id: get-tag-step
      - name: create commit
        run: |
          echo "Update go.mod and go.sum to latest version from ${{ github.repository }}@${{ steps.get-tag-step.outputs.tag }}" >> /tmp/commit-message
      - name: Checkout denis-tingaikin/${{ matrix.repository }}
        uses: actions/checkout@v2
        with:
          path: denis-tingaikin/${{ matrix.repository }}
          repository: denis-tingaikin/${{ matrix.repository }}
          token: ${{ secrets.MY_TOKEN }}
      - uses: actions/setup-go@v1
        with:
          go-version: 1.16
      - name: Update ${{ github.repository }} locally
        working-directory: denis-tingaikin/${{ matrix.repository }}
        run: |
          GOPRIVATE=github.com/denis-tingaikin go get -u github.com/${{ github.repository }}@${{ steps.get-tag-step.outputs.tag }}
          go mod tidy
          git diff
      - name: Push update to the ${{ matrix.repository }}
        working-directory: denis-tingaikin/${{ matrix.repository }}
        run: |
          echo Starting to update repositotry ${{ matrix.repository }}
          git config --global user.email "denis@tingajkin@xored.com"
          git config --global user.name "denis.tingaikin"
          git add go.mod go.sum
          git commit -s -F /tmp/commit-message
          git checkout -b ${{ github.event.workflow_run.head_branch }}
          git push -f origin ${{ github.event.workflow_run.head_branch }}
