---
name: Release
on:
  push:
    branches:
      - 'release/**'
jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Get tag
        run: echo '::set-output name=tag::'${GITHUB_REF#refs/heads/release/}
        id: get-tag-step
      - uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true # default: false
          tag_name: ${{ steps.get-tag-step.outputs.tag }}
          repo: ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
        with:
          tag_name: ${{ steps.get-tag-step.outputs.tag }}
          release_name: Release ${{ steps.get-tag-step.outputs.tag }}
          draft: false
          prerelease: false
