---
name: Release
on:
  workflow_run:
    types:
      - completed
    workflows:
      - 'ci'
jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.actor == 'denis.tingaikin' && contains(github.ref, 'refs/heads/release/') }}
    steps:
      - name: Get tag
        run: echo '::set-output name=tag::'${GITHUB_REF#refs/heads/release/}
        id: get-tag-step
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
        with:
          tag_name: ${{ steps.get-tag-step.outputs.tag }}
          release_name: ${{ steps.get-tag-step.outputs.tag }}
          draft: false
          prerelease: false
  update-dependent-repositories:
    strategy:
      matrix:
        repository:
          - actions-testing-repository-b
    name: Update ${{ matrix.repository }}
    needs: create-release
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.actor == 'denis.tingaikin' && contains(github.ref, 'refs/heads/release/') }}
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v2
        with:
          path: ${{ github.repository }}
          repository: ${{ github.repository }}
          token: ${{ secrets.MY_TOKEN }}
        working-directory: ${{ github.repository }}
      - name: create commit
        run: |
          echo "Update go.mod and go.sum to latest version from ${{ github.repository }}@${GITHUB_REF#refs/heads/release/}" >> /tmp/commit-message
      - name: Checkout denis-tingaikin/${{ matrix.repository }}
        uses: actions/checkout@v2
        with:
          path: denis-tingaikin/${{ matrix.repository }}
          repository: denis-tingaikin/${{ matrix.repository }}
          token: ${{ secrets.MY_TOKEN }}
      - uses: actions/setup-go@v1
        with:
          go-version: 1.16
      - name: Update ${{ github.repository }} locally
        working-directory: denis-tingaikin/${{ matrix.repository }}
        run: |
          GOPRIVATE=github.com/denis-tingaikin go get -u github.com/${{ github.repository }}@${GITHUB_REF#refs/heads/release/}
          go mod tidy
          git diff
      - name: Push update to the ${{ matrix.repository }}
        working-directory: denis-tingaikin/${{ matrix.repository }}
        run: |
          echo Starting to update repositotry ${{ matrix.repository }}
          git config --global user.email "denis@tingajkin@xored.com"
          git config --global user.name "denis.tingaikin"
          git add go.mod go.sum
          git commit -s -F /tmp/commit-message
          git checkout -b ${GITHUB_REF#refs/heads/}
          git push -f origin ${GITHUB_REF#refs/heads/}
