---
name: Release
on:
  push:
    branches:
      - 'release/**'
jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Get tag
        run: echo '::set-output name=tag::'${GITHUB_REF#refs/*/}
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
        with:
          tag_name: ${{ steps.get-tag-step.outputs.tag }}
          release_name: Release ${{ steps.get-tag-step.outputs.tag }}
          draft: false
          prerelease: false
  update-dependent-repositories:
    strategy:
      matrix:
        repository: [actions-testing-repository-b]
    name: Update ${{ matrix.repository }}
    needs: create-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v2
        with:
          path: ${{ github.repository }}
          repository: ${{ github.repository }}
          token: ${{ secrets.MY_TOKEN }}
      - name: Find merged PR
        uses: jwalton/gh-find-current-pr@v1
        id: findPr
        with:
          github-token: ${{ github.token }}